name: Package application-generic Tests

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  integration_application_generic:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 80

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/setup-project

    - uses: mansagroup/nrwl-nx-action@v3
      with:
        targets: lint
        projects: '@novu/application-generic'

    # - uses: ./.github/actions/start-localstack

      # Runs a single command using the runners shell
    - name: Build application-generic
      run: cd packages/application-generic && CI='' pnpm build

    # Runs a set of commands using the runners shell
    - name: Run the tests
      run: cd packages/application-generic && pnpm test
